# Generated by Django 4.2.5 on 2023-09-25 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePageApp', '0002_alter_dateperson_numberphon'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateperson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 21, 11, 50, 565009)),
        ),
        migrations.AlterField(
            model_name='dateperson',
            name='numberPhon',
            field=models.TextField(max_length=10),
        ),
    ]
